### ISSUE TITLE
Custom Speaker EQ Configurations

### ISSUE THREAD

**Issue by sameleff** [thomaseleff/AutoEq-Device-Manager#33]
Create a method to create custom EQ configs (e.g. for speakers [not IEM's/headphones], or for IEM's/headphones that do not already have APO profiles).
Additionally, allow the user to create a default profile/config (including no profile) for each audio output device with APO installed.

**Comment by thomaseleff** [comment]
May be able to bucket this into a broader feature... a new setting, which will raise a new form to associate connected audio devices with a "type", like "Speaker", "Headphone", "Line-Out", a default EQ profile (select-able from a set list of profiles present within the /config folder)

**Comment by thomaseleff** [comment]
This was implemented as a settings feature, storing settings within the registry for any discovered audio playback device and equalizer profile over the lifetime of the application. Therefore, no change to the naming convention of the equalizer profiles was made, as the device type and other settings are stored in the registry.

All settings are defaulted upon initialization of the system-tray tool but can be configured. Therefore, the system-tray tool is always expected to be built even when the user wishes to not supply non-default configuration.
